apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-green
  namespace: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-green
  template:
    metadata:
      labels:
        app: blue-green
    spec:
      containers:
        - name: blue-green
          image: imishrarohit/blue-green:latest 
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  namespace: blue
spec:
  selector:
    app: blue-green
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer
